good/urls.py
from django.conf.urls import url
from . import views

app_name = 'good'

urlpatterns = [
    # /good/
    url (r'^$',  views.index, name='index'),
    # /good/156
    url (r'^(?P<category_id>[0-9]+)/$', views.detail, name='detail'),
    # /good/156/favorite
    url (r'^(?P<category_id>[0-9]+)/favorite$', views.favorite, name='favorite'),
]

goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url (r'^$',  views.index, name='index'),
    # /goods/156
    url (r'^(?P<category_id>[0-9]+)/$', views.detail, name='detail')
]

killolx/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^good/', include('good.urls')),
]

komerco/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^listing/', include('listing.urls')),
]

listing/urls.py
from django.conf.urls import url
from . import views

app_name = 'listing'

urlpatterns = [
    # /listing/
    url (r'^$',  views.IndexView.as_view(), name='index'),
    # /listing/156
    url  (r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /listing/156/favorite
    #url (r'^(?P<category_id>[0-9]+)/favorite$', views.favorite, name='favorite'),

    # /listing/category/add
    url (r'category/add/$', views.CategoryCreate.as_view(), name='category-add'),

    # /listing/category/2
    url (r'category/(?P<pk>[0-9]+)/$', views.CategoryUpdate.as_view(), name='category-update'),
    # /listing/category/2/delete
    url (r'category/(?P<pk>[0-9]+)/delete$', views.CategoryDelete.as_view(), name='category-delete'),
]

good/models.py
from django.db import models

# pk 1
class Category(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    category_logo = models.CharField(max_length=600)
    def __str__(self):
        return self.name + ' - ' + self.description

class Good(models.Model):
    author = models.CharField(max_length=250)
    good_title = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.author + ' - ' + self.good_title

goods/models.py
from django.db import models

# pk 1
class Category(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    category_logo = models.CharField(max_length=600)


    def __str__(self):
        return self.name + ' - ' + self.description

class Goods(models.Model):
    author = models.CharField(max_length=250)
    good_title = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

listing/models.py
from django.db import models
from django.urls import reverse

# pk 1
class Category(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    category_logo = models.CharField(max_length=600)
    def get_absolute_url(self):
        return reverse('listing:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' - ' + self.description

class Listing(models.Model):
    author = models.CharField(max_length=250)
    listing_title = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=20)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.author + ' - ' + self.listing_title

listing/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Category, Listing


class IndexView(generic.ListView):
    template_name = 'listing/index.html'
    context_object_name = 'all_categories'
    def get_queryset(self):
        return Category.objects.all()

class DetailView(generic.DetailView):
    model = Category
    template_name = 'listing/detail.html'


class CategoryCreate(CreateView):
    model = Category
    fields = ['name', 'description', 'category_logo']

class CategoryUpdate(UpdateView):
    model = Category
    fields = ['name', 'description', 'category_logo']

class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('listing:index')

good/templates/good/index.html
{% load static %}
<link rel="stylesheet" href="{% static   'good/style.css'%}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="{% url 'good:index' %}" class="navbar-brand">Komerco</a>
        </div>
    </div>
</nav>

{% if all_categories %}
    <h3>Here are all my categories</h3>
    <ul>
        {% for category in all_categories %}
        <li><a href="{% url 'good:detail' category.id %}">{{category.name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any categories</h3>
{% endif %}

goods/templates/goods/index.html
{% if all_categories %}
    <ul>
        {% for category in all_categories %}
        <li><a href="/goods/{{ category.id }}/">{{category.name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any categories</h3>
{% endif %}

listing/templates/listing/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Komerco{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='//fonts.googleapis.com/css?family=Roboto:400,700,400italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static  'listing/style.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'listing:index' %}" class="navbar-brand">Komerco</a>
        </div>


        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block categories_active %}{% endblock %}" >
                    <a href="{% url 'listing:index' %}">
                        <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp;
                        Categories
                    </a>
                </li>

                <li class="{% block listings_active %}{% endblock %}" >
                    <a href="{% url 'listing:index' %}">
                        <span class="glyphicon" aria-hidden="true"></span>&nbsp;
                        Listings
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'listing:category-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Category
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}

{% endblock %}

</body>
</html>

listing/templates/listing/category_form.html
{% extends 'listing/base.html' %}
{% block title %}Add a New Category {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'listing/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Komerco ?</h3>
                    <p>Komerco is an app that allows you to sell or buy items/products on the internet.</p>
                    <h3>How do I add an item?</h3>
                    <p>First, create a new category by filling out the form on this page. Once a category is created you will be able to add items.</p>
                    <h3>What are some Category logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

listing/templates/listing/detail.html
{% extends 'listing/base.html' %}
{% block title %}Category Details{% endblock %}
{% block body %}


<div class="container-fluid songs-container">
    <div class="row">
        <!-- Left Category Info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'listing:detail' category.id %}">
                        {% if category.category_logo %}
                            <img src="{{category.category_logo}}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ category.name }} <small>{{ category.description }}</small> </h1>
                </div>
            </div>
        </div>

        <!-- Right Category Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'listing:detail' category.id %}">View All</a></li>
                <!--li role="presentation"><a href="{% url 'listing:listing-add' category.id  %}">Add New Listing</a></li-->
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>All Listings</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message}}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thread>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Telephone</th>
                                <th>Category</th>
                            </tr>
                        </thread>
                        <tbody>
                            {% for listing in category.listing.all %}
                                <tr>
                                    <td>
                                        {{listing.listing_title}}
                                    </td>
                                    <td></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
    </div>
</div>

    <img src="{{ category.category_logo }}" style="width: auto; height: 150px;" alt="">
    <h1>{{ category.name }}</h1>
    <h3>{{ category.description }}</h3>


        {% for listing in category.listing.all %}
            <input type="radio" id="listing{{ forloop.counter }}" name="listing" value="{{listing.id}}"/>
            <label for="listing{{ forloop.counter }}">
                {{ listing.listing_title }}
            </label>
                {% if listing.is_favorite %}
                    <img src="http://i.imgur.com/b9b13Rd.png" alt=""/>
                {% endif %}
            <br>
        {% endfor %}


    <a href="{% url 'listing:index'  %}">Back</a>

{% endblock %}

listing/templates/listing/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label  class="control-label col-sm-2">{{ field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

listing/templates/listing/index.html
{% extends 'listing/base.html' %}
{% block categories_active %}active{% endblock %}

{% block body %}
<div class="categories-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Categories</h3>
        </div>

        {% if all_categories %}
            {% for category in all_categories %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'listing:detail' category.id %}">
                            <img src="{{ category.category_logo }}" alt="" style="width: auto; height: 150px;" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ category.name }}</h2>
                            <h4>{{ category.description }}</h4>
                            <!-- view details -->
                            <a href="{% url 'listing:detail' category.id %}" class="btn btn-primary btn-sm" role="button">
                                View Details
                            </a>
                            <!-- delete album -->
                            <form action="{% url 'listing:category-delete'  category.id%}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="category_id" value="{{ category.id}}">
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash">

                                    </span>
                                </button>
                            </form>


                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if category.is_favorite %}active{% endif %}"></span>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'listing:category-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

</div>





        <!--ul>
            {% for category in all_categories %}
            <li><a href="{% url 'listing:detail' category.id %}">{{category.name}}</a></li>
            {% endfor %}
        </ul-->
{% endblock %}